# -*- coding: utf-8 -*-
"""Time moduleipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbkFGLesovS-QErsDR2nOZrIwv07k8_6

**Reminder time :**
"""

import datetime

# Get current time
current_time = datetime.datetime.now()
hour = current_time.hour   # Get the hour (0-23 format)

print(f"Current time: {current_time.strftime('%I:%M %p')}")

# Reminder using if-else
if 5 <= hour < 12:
    print("Good Morning! It's morning time.")
elif 12 <= hour < 17:
    print("Good Afternoon! It's afternoon time.")
elif 17 <= hour < 20:
    print("Good Evening! It's evening time.")
else:
    print("Good Night! It's night time.")